name: Generate gRPC Code Via Buf
on:
  push:
    branches: [main]

jobs:
  buf:
    runs-on: ubuntu-latest
    steps:
      # Run `git checkout`
      - uses: actions/checkout@v4
      # Install the `buf` CLI
      - uses: bufbuild/buf-setup-action@v1.50.0
      # Run `buf generate`
      - name: Generate gRPC Code
        run: |
          buf --version
          buf generate
      # Update go.mod
      - uses: actions/setup-go@v5
      - run: go mod tidy
      - name: commit
        run: |
          [[ ! $(git diff --exit-code gen/go) ]] && echo "Nothing to commit." && exit 0
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull
          git add gen/go
          git commit -m "BOT: regenerate grpc code"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check Swift Code
        run: |
          [[ ! $(git diff --exit-code Sources) ]] && echo "Nothing to commit." && exit 0
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull
          git add Sources
          git commit -m "BOT: regenerate grpc code"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}