name: Generate gRPC Code Via Buf
on:
  push:
    branches: [main]

jobs:
  buf:
    runs-on: ubuntu-latest
    steps:
      # Run `git checkout`
      - uses: actions/checkout@v4
      # Install the `buf` CLI
      - uses: bufbuild/buf-setup-action@v1.50.0
      # Run `buf generate`
      - run: buf generate
      # Update go.mod
      - uses: actions/setup-go@v5
      - run: go mod tidy