name: Generate gRPC Code Via Buf
on:
  push:
    branches: [main]

jobs:
  buf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@v1
        with:
          setup_only: true
      - run: buf generate
      - uses: actions/setup-go@v5
      - name: Install dependencies
        run: |
          go mod tidy